### ISSUE TITLE
[Hearth update] A few bugs!

### ISSUE THREAD

**Issue by Ski-z** [Rebirth-of-the-Night/ExSartagine-Requiem#4]
1. **When breaking some container blocks, nothing drops from within them.** For example, a whole stack of iron ore waiting to smelt will be lost if the smelter is broken.
2. ~~I can't seem to get extensions to work. In previous release, they worked no problem.~~ Confirmed, extensions are separate non-automatic block!
3. **Kettle, Cooking Pot and Smelter all have different non-uniform item sizes when thrown on the ground.**
4. Cannot remove items from Wok. If you accidenally right-click an item into the wok, it is stuck there. You CAN break it to get your item(s) back, but it seems like maybe something like shift-right-click should remove the placed items. For example, I find myself often accidentally placing a wok in my wok, which I can't remove without breaking the wok itself.
5. Craft Tweaker method `'addPlaceableNonSolid IBlockState'` Doesn't seem to work

**Comment by Foreck1** [comment]
For 4, shift + left click works for removing items

**Comment by Foreck1** [comment]
Should all be fixed with 0.3.10
